// <auto-generated />
using ConsoleApp3.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp3.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210409085956_0409")]
    partial class _0409
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ConsoleApp3.models.total_amount", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.Property<float>("Per")
                        .HasColumnType("float")
                        .HasMaxLength(30);

                    b.Property<float>("Roe")
                        .HasColumnType("float")
                        .HasMaxLength(30);

                    b.Property<int>("diff")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.Property<float>("forign")
                        .HasColumnType("float")
                        .HasMaxLength(30);

                    b.Property<string>("name")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<int>("one_price")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.Property<int>("price")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.Property<string>("rate")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<int>("total_price")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.Property<int>("total_size")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.Property<int>("volume")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.HasKey("number");

                    b.ToTable("total_amounts");
                });
#pragma warning restore 612, 618
        }
    }
}
